# Generated by Django 4.2 on 2023-04-29 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_translatormodel_delete_translationcache'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TranslatorModel',
        ),
    ]
